for lin in range (0,4):
    for col in range(0,4):
        if lin%2 == 0 and col%2 == 0:
            print("\tnext(board[{0}][{1}]) := case".format(lin,col))
            print("\t\t\t\t\t\t\tlin = {0} & col = {1} & (canMove): 0;".format(lin,col))
            print("\t\t\t\t\t\t\tcanMove & whoIs = 1 & {0} = linUp:case".format(lin))
            print("\t\t\t\t\t\t\t\t {0} = diagDir: 1;".format(col))
            print("\t\t\t\t\t\t\t\t {0} = diagEsq: 1;".format(col))
            print("\t\t\t\t\t\t\t\t TRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t\t\tesac;")
            print("\t\t\t\t\t\t\tcanMove & whoIs = 2 & {0} = linDw:case".format(lin))
            print("\t\t\t\t\t\t\t\t {0} = diagDir: 3;".format(col))
            print("\t\t\t\t\t\t\t\t {0} = diagEsq: 3;".format(col))
            print("\t\t\t\t\t\t\t\t TRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t\t\tesac;")
            print("\t\t\t\t\t\t\tTRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t esac;")
        elif lin%2 == 1 and col%2 == 1:
            print("\tnext(board[{0}][{1}]) := case".format(lin,col))
            print("\t\t\t\t\t\t\tlin = {0} & col = {1} & (canMove): 0;".format(lin,col))
            print("\t\t\t\t\t\t\tcanMove & whoIs = 1 & {0} = linUp:case".format(lin))
            print("\t\t\t\t\t\t\t\t {0} = diagDir: 1;".format(col))
            print("\t\t\t\t\t\t\t\t {0} = diagEsq: 1;".format(col))
            print("\t\t\t\t\t\t\t\t TRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t\t\tesac;")
            print("\t\t\t\t\t\t\tcanMove & whoIs = 2 & {0} = linDw:case".format(lin))
            print("\t\t\t\t\t\t\t\t {0} = diagDir: 3;".format(col))
            print("\t\t\t\t\t\t\t\t {0} = diagEsq: 3;".format(col))
            print("\t\t\t\t\t\t\t\t TRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t\t\tesac;")
            print("\t\t\t\t\t\t\tTRUE: board[{0}][{1}];".format(lin,col))
            print("\t\t\t\t\t\t esac;")
        else:
            print("\tnext(board[{0}][{1}]) := board[{0}][{1}];".format(lin,col))
